	<div class="table-wrapper lowered_30">
		<table>
			<thead>
				<tr>
					<th>Год</th>
					<th>Сертификат</th>
					<th>Кем выдан</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>2019</td>
					<td><a href="/petrova/education/certificate/english" target ="blank" class="blue">Английский. Продвинутый</a></td>
					<td>englishdom.ru</td>
				</tr>
				<tr>
					<td>2019</td>
					<td><a href="https://geekbrains.ru/go/69WG4F" target ="blank" class="blue">JavaScript. Средний уровень</a></td>
					<td>GeekBrains</td>
				</tr>
				<tr>
					<td>2018</td>
					<td><a href="https://geekbrains.ru/go/6u7OhL" target ="blank" class="blue">HTML&CSS. Сложный уровень</a></td>
					<td>GeekBrains</td>
				</tr>
				<tr>
					<td>2018</td>
					<td><a href="https://geekbrains.ru/go/OFaIhn" target ="blank" class="blue">Python. Начальный уровень</a></td>
					<td>GeekBrains</td>
				</tr>
				<tr>
					<td>2017</td>
					<td><a href="https://geekbrains.ru/go/zyWG6J" target ="blank" class="blue">PHP. Начальный уровень</a></td>
					<td>GeekBrains</td>
				</tr>
			</tbody>
		</table>
	</div>
