<div class="header-left">
    <a href="/petrova/rezume"><img src="/public/img/avatar.jpg" class="header-left__avatar"/></a>
    <h2 class="header-left__txt"><a href ="/petrova">Петрова<span class="header-left__subname"> Татьяна Владимировна</span></a></h2>
    <div class="header-left__contacts">
        <p>+7 903 0432 733</p>
        <p class="header-left__gap_display"> | </p>
        <p class="lowered_0">ta197@mail.ru</p>
    </div>
</div>