<div class="category-bigmenu category-bigmenu_three side-left">
    <ul>
	    <li>
	        <ul>
                <li><a href="/petrova/rezume/develop/example/metr#idea">идея сайта</a></li>
                <li><a href="/petrova/rezume/develop/example/metr#cat">о разделе "Категории"</a></li>
                <li><a href="/petrova/rezume/develop/example/metr#filter">о разделе "Компании" (AJAX)</a></li>
                <li><a href="/petrova/rezume/develop/example/metr#search">о разделе "Поиск"</a></li>
                <li><a href="/petrova/rezume/develop/example/metr#mvc">архитектура (MVC)</a></li>
                <li><a href="/petrova/rezume/develop/example/metr#sql">база данных (SQL)</a></li>
	        </ul>
	    </li>
	    <li>
	        <ul>
		        <li><a href="/petrova/rezume/develop/example/metr#bem">наименование стилей</a></li>
                <li><a href="/petrova/rezume/develop/example/metr#adaptiv">адаптивность и кроссбраузерность</a></li>
                <li><a href="/petrova/rezume/develop/example/metr#design">дизайн</a></li>
		        <li><a href="/petrova/rezume/develop/example/metr#git">git</a></li>
	        </ul>
	    </li>
    </ul>
</div>