	<div class="table-wrapper lowered_30">
		<table>
			<thead>
				<tr>
					<th>Год</th>
					<th>Сертификат</th>
				</tr>
			</thead>
			<tbody>
					<td>2019</td>
					<td><a href="https://geekbrains.ru/go/69WG4F" target ="blank" class="link-dashed blue">JavaScript. Средний уровень</a></td>
				</tr>
				<tr>
					<td>2018</td>
					<td><a href="https://geekbrains.ru/go/6u7OhL" target ="blank" class="link-dashed blue">HTML&CSS. Сложный уровень</a></td>
				</tr>
				<tr>
					<td>2018</td>
					<td><a href="https://geekbrains.ru/go/OFaIhn" target ="blank" class="link-dashed blue">Python. Начальный уровень</a></td>
				</tr>
				<tr>
					<td>2017</td>
					<td><a href="https://geekbrains.ru/go/zyWG6J" target ="blank" class="link-dashed blue">PHP. Начальный уровень</a></td>
				</tr>
			</tbody>
		</table>
	</div>