 <div class="side-content">
    <section class="section__hr"> 
        <h2 >Контакты</h2>
	</section> 
</div>

<div class="category-bigmenu category-bigmenu_three side-left">
	<ul>
		<li><h4>Предпочтительно</h4>
			<ul>
				<li>e-mail: ta197@mail.ru</li>
				<li>тел. +7 903 0432 733</li>
			</ul>
		</li>
		<li><h4>Соцсети</h4>
			<ul>
				<li><a href="https://vk.com/ta197">ВКонтакте</a></li>
                <li><a href="https://ok.ru/profile/558561760000">ОК</a></li>
			</ul>
		</li>
	<!--	<li><h4>На всякий случай</h4>
			<ul>
				<li><a href="https://github.com/ta197">github</a></li>
			</ul>
		</li>-->
	</ul>
</div>