<footer>
    <div class="footer__content">
        <div class="side-content">
           
<ul class="footer__column">
        <li class="footer__column-item"><a  href="/">на сайт</a></li><br/>
        <li class="footer__column-item"><a  href="/admin/users/logout">выход</a></li>
    </ul>

 <ul class="footer__column">
        <li class="footer__column-item"><a  href="/admin/users/login">регистрация</a></li><br/>
        <li class="footer__column-item"><a  href="/admin/users/login">вход</a></li>
    </ul>

    <ul class="footer__column">
        <li class="footer__column-item"><a  href="/petrova">&copy; Петрова Т.В., 2017-2018</a></li>
    </ul>
    </div>
</div> <!--закрытие footer__content-->
        
</footer>
        
<div id ="updown">
    <a href="#">
        <div class="updown up"> </div>
    </a>
</div>
    <!-- <script type="text/javascript" src="/js/updown.js" type="text/javascript"></script> -->