<!DOCTYPE html>
<html lang="ru-Ru">
<head>
    <meta charset="UTF-8">
    <title><?=$title?></title>
    <link rel="stylesheet" href="/css/style.css" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script type="text/javascript" src="/js/smoothscroll.js" type="text/javascript"></script>
    <script type="text/javascript" src="/js/updown.js" type="text/javascript" defer></script>
    
</head>
