<div class="listing side-content">

    <table>
        <tr>
            <td>role</td>
            <td><?=$user->role?></td>
        </tr>
       
        <tr>
            <td>id</td>
            <td><?=$user->id?></td>
        </tr>
        <tr>
            <td>Логин</td>
            <td><?=$user->login ?></td>
        </tr>
        <tr>
            <td>имя</td>
            <td><?=$user->name?></td>
        </tr>
        <tr>
            <td>email</td>
            <td><?=$user->email?></td>
        </tr>
</table>
</div>